apiVersion: v1
kind: ConfigMap
metadata:
  name: supportsphere-config
  namespace: supportsphere
data:
  POSTGRES_SERVER: "postgres-service"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "supportsphere"
  POSTGRES_PORT: "5432"
  API_V1_STR: "/api"
